const data = [
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [5] },
  { SLOTID: "SLOTID4", STATUS: "Good", ALERTNODES: [11, 13] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [4, 15] },
  { SLOTID: "SLOTID3", STATUS: "Average", ALERTNODES: [14, 15] },
  { SLOTID: "SLOTID1", STATUS: "Degraded", ALERTNODES: [15] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [4, 8, 11] },
  { SLOTID: "SLOTID3", STATUS: "Degraded", ALERTNODES: [3] },
  { SLOTID: "SLOTID2", STATUS: "Degraded", ALERTNODES: [9, 12, 13] },
  { SLOTID: "SLOTID8", STATUS: "Start to degrade", ALERTNODES: [3, 10, 11] },
  { SLOTID: "SLOTID4", STATUS: "Start to degrade", ALERTNODES: [1, 10] },
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [1] },
  { SLOTID: "SLOTID4", STATUS: "Start to degrade", ALERTNODES: [6] },
  { SLOTID: "SLOTID4", STATUS: "Start to degrade", ALERTNODES: [5] },
  { SLOTID: "SLOTID7", STATUS: "Start to degrade", ALERTNODES: [1, 14] },
  { SLOTID: "SLOTID4", STATUS: "Good", ALERTNODES: [1, 7, 9] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [7] },
  { SLOTID: "SLOTID8", STATUS: "Average", ALERTNODES: [14] },
  { SLOTID: "SLOTID5", STATUS: "Degraded", ALERTNODES: [7] },
  { SLOTID: "SLOTID1", STATUS: "Start to degrade", ALERTNODES: [6] },
  { SLOTID: "SLOTID4", STATUS: "Start to degrade", ALERTNODES: [13] },
  { SLOTID: "SLOTID1", STATUS: "Degraded", ALERTNODES: [10] },
  { SLOTID: "SLOTID4", STATUS: "Degraded", ALERTNODES: [4, 10] },
  { SLOTID: "SLOTID3", STATUS: "Start to degrade", ALERTNODES: [3, 9, 14] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [3, 8] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [4] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [2, 4, 16] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [6, 16] },
  { SLOTID: "SLOTID6", STATUS: "Start to degrade", ALERTNODES: [9, 12] },
  { SLOTID: "SLOTID3", STATUS: "Average", ALERTNODES: [2, 6] },
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [8, 11, 16] },
  { SLOTID: "SLOTID7", STATUS: "Start to degrade", ALERTNODES: [4, 14] },
  { SLOTID: "SLOTID1", STATUS: "Start to degrade", ALERTNODES: [7, 11] },
  { SLOTID: "SLOTID6", STATUS: "Good", ALERTNODES: [12, 13] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [6, 13] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [13] },
  { SLOTID: "SLOTID5", STATUS: "Average", ALERTNODES: [1, 4] },
  { SLOTID: "SLOTID6", STATUS: "Degraded", ALERTNODES: [8, 14, 16] },
  { SLOTID: "SLOTID4", STATUS: "Average", ALERTNODES: [1, 14] },
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [4, 7] },
  { SLOTID: "SLOTID4", STATUS: "Good", ALERTNODES: [2, 3, 13] },
  { SLOTID: "SLOTID4", STATUS: "Good", ALERTNODES: [4] },
  { SLOTID: "SLOTID6", STATUS: "Degraded", ALERTNODES: [11] },
  { SLOTID: "SLOTID5", STATUS: "Good", ALERTNODES: [4] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [6, 14] },
  { SLOTID: "SLOTID1", STATUS: "Degraded", ALERTNODES: [3, 8] },
  { SLOTID: "SLOTID6", STATUS: "Good", ALERTNODES: [12] },
  { SLOTID: "SLOTID3", STATUS: "Degraded", ALERTNODES: [11, 13, 16] },
  { SLOTID: "SLOTID4", STATUS: "Good", ALERTNODES: [6, 10] },
  { SLOTID: "SLOTID5", STATUS: "Average", ALERTNODES: [3, 11, 15] },
  { SLOTID: "SLOTID5", STATUS: "Degraded", ALERTNODES: [1, 11] },
  { SLOTID: "SLOTID3", STATUS: "Average", ALERTNODES: [4, 15] },
  { SLOTID: "SLOTID1", STATUS: "Average", ALERTNODES: [8, 9] },
  { SLOTID: "SLOTID4", STATUS: "Good", ALERTNODES: [2, 4, 15] },
  { SLOTID: "SLOTID4", STATUS: "Degraded", ALERTNODES: [4, 6, 13] },
  { SLOTID: "SLOTID7", STATUS: "Average", ALERTNODES: [10, 12] },
  { SLOTID: "SLOTID7", STATUS: "Start to degrade", ALERTNODES: [12] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [1, 6] },
  { SLOTID: "SLOTID5", STATUS: "Good", ALERTNODES: [12, 16] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [2, 7] },
  { SLOTID: "SLOTID4", STATUS: "Good", ALERTNODES: [2, 12, 14] },
  { SLOTID: "SLOTID8", STATUS: "Good", ALERTNODES: [3, 13] },
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [10] },
  { SLOTID: "SLOTID5", STATUS: "Average", ALERTNODES: [7, 10, 12] },
  { SLOTID: "SLOTID4", STATUS: "Degraded", ALERTNODES: [7] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [5, 9, 13] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [9, 12] },
  { SLOTID: "SLOTID7", STATUS: "Start to degrade", ALERTNODES: [6, 11] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [5, 6, 10] },
  { SLOTID: "SLOTID6", STATUS: "Average", ALERTNODES: [9, 10, 14] },
  { SLOTID: "SLOTID6", STATUS: "Good", ALERTNODES: [5, 8] },
  { SLOTID: "SLOTID8", STATUS: "Good", ALERTNODES: [13, 14, 16] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [6, 8] },
  { SLOTID: "SLOTID4", STATUS: "Good", ALERTNODES: [11] },
  { SLOTID: "SLOTID5", STATUS: "Average", ALERTNODES: [3, 8, 9] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [9] },
  { SLOTID: "SLOTID1", STATUS: "Good", ALERTNODES: [1, 4, 12] },
  { SLOTID: "SLOTID4", STATUS: "Good", ALERTNODES: [2, 5, 8] },
  { SLOTID: "SLOTID6", STATUS: "Good", ALERTNODES: [12] },
  { SLOTID: "SLOTID3", STATUS: "Degraded", ALERTNODES: [9] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [1] },
  { SLOTID: "SLOTID1", STATUS: "Start to degrade", ALERTNODES: [5, 16] },
  { SLOTID: "SLOTID8", STATUS: "Start to degrade", ALERTNODES: [1, 4, 13] },
  { SLOTID: "SLOTID4", STATUS: "Average", ALERTNODES: [2] },
  { SLOTID: "SLOTID8", STATUS: "Good", ALERTNODES: [5] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [3, 4, 16] },
  { SLOTID: "SLOTID2", STATUS: "Degraded", ALERTNODES: [3, 9, 16] },
  { SLOTID: "SLOTID2", STATUS: "Degraded", ALERTNODES: [12] },
  { SLOTID: "SLOTID5", STATUS: "Average", ALERTNODES: [1, 7] },
  { SLOTID: "SLOTID4", STATUS: "Degraded", ALERTNODES: [6] },
  { SLOTID: "SLOTID8", STATUS: "Start to degrade", ALERTNODES: [5, 8, 13] },
  { SLOTID: "SLOTID4", STATUS: "Degraded", ALERTNODES: [1, 10] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [4, 14] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [3, 6, 13] },
  { SLOTID: "SLOTID1", STATUS: "Degraded", ALERTNODES: [4, 16] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [12] },
  { SLOTID: "SLOTID7", STATUS: "Degraded", ALERTNODES: [4, 9] },
  { SLOTID: "SLOTID1", STATUS: "Start to degrade", ALERTNODES: [2] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [5] },
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [13, 14] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [8] },
  { SLOTID: "SLOTID2", STATUS: "Good", ALERTNODES: [5] },
  { SLOTID: "SLOTID8", STATUS: "Start to degrade", ALERTNODES: [2, 6] },
  { SLOTID: "SLOTID2", STATUS: "Good", ALERTNODES: [7, 10, 11] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [2] },
  { SLOTID: "SLOTID4", STATUS: "Good", ALERTNODES: [7] },
  { SLOTID: "SLOTID8", STATUS: "Good", ALERTNODES: [11] },
  { SLOTID: "SLOTID6", STATUS: "Start to degrade", ALERTNODES: [5, 11] },
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [6, 7] },
  { SLOTID: "SLOTID7", STATUS: "Average", ALERTNODES: [3, 9] },
  { SLOTID: "SLOTID5", STATUS: "Good", ALERTNODES: [7] },
  { SLOTID: "SLOTID8", STATUS: "Start to degrade", ALERTNODES: [6, 14] },
  { SLOTID: "SLOTID1", STATUS: "Good", ALERTNODES: [8, 10, 16] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [10] },
  { SLOTID: "SLOTID6", STATUS: "Degraded", ALERTNODES: [10] },
  { SLOTID: "SLOTID3", STATUS: "Degraded", ALERTNODES: [9, 10, 15] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [11] },
  { SLOTID: "SLOTID2", STATUS: "Start to degrade", ALERTNODES: [5, 11, 16] },
  { SLOTID: "SLOTID4", STATUS: "Average", ALERTNODES: [7, 8, 15] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [1] },
  { SLOTID: "SLOTID8", STATUS: "Start to degrade", ALERTNODES: [3, 13] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [14] },
  { SLOTID: "SLOTID8", STATUS: "Good", ALERTNODES: [13, 16] },
  { SLOTID: "SLOTID1", STATUS: "Average", ALERTNODES: [13] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [7, 11] },
  { SLOTID: "SLOTID4", STATUS: "Start to degrade", ALERTNODES: [2, 16] },
  { SLOTID: "SLOTID6", STATUS: "Degraded", ALERTNODES: [10] },
  { SLOTID: "SLOTID8", STATUS: "Start to degrade", ALERTNODES: [9] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [5] },
  { SLOTID: "SLOTID5", STATUS: "Average", ALERTNODES: [14] },
  { SLOTID: "SLOTID2", STATUS: "Start to degrade", ALERTNODES: [16] },
  { SLOTID: "SLOTID5", STATUS: "Degraded", ALERTNODES: [10, 11] },
  { SLOTID: "SLOTID6", STATUS: "Degraded", ALERTNODES: [5, 10, 11] },
  { SLOTID: "SLOTID7", STATUS: "Degraded", ALERTNODES: [7] },
  { SLOTID: "SLOTID6", STATUS: "Good", ALERTNODES: [9] },
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [14] },
  { SLOTID: "SLOTID6", STATUS: "Average", ALERTNODES: [1] },
  { SLOTID: "SLOTID5", STATUS: "Degraded", ALERTNODES: [1, 6] },
  { SLOTID: "SLOTID2", STATUS: "Start to degrade", ALERTNODES: [1] },
  { SLOTID: "SLOTID1", STATUS: "Start to degrade", ALERTNODES: [4, 10, 16] },
  { SLOTID: "SLOTID7", STATUS: "Average", ALERTNODES: [1, 14] },
  { SLOTID: "SLOTID8", STATUS: "Good", ALERTNODES: [7, 14] },
  { SLOTID: "SLOTID1", STATUS: "Good", ALERTNODES: [12, 13] },
  { SLOTID: "SLOTID8", STATUS: "Good", ALERTNODES: [4, 12, 16] },
  { SLOTID: "SLOTID1", STATUS: "Start to degrade", ALERTNODES: [6, 11] },
  { SLOTID: "SLOTID8", STATUS: "Start to degrade", ALERTNODES: [8, 15] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [15] },
  { SLOTID: "SLOTID8", STATUS: "Good", ALERTNODES: [1, 5] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [8] },
  { SLOTID: "SLOTID5", STATUS: "Good", ALERTNODES: [1, 11] },
  { SLOTID: "SLOTID2", STATUS: "Start to degrade", ALERTNODES: [11, 13] },
  { SLOTID: "SLOTID8", STATUS: "Start to degrade", ALERTNODES: [7, 9, 16] },
  { SLOTID: "SLOTID2", STATUS: "Good", ALERTNODES: [7, 9, 14] },
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [2, 6, 15] },
  { SLOTID: "SLOTID6", STATUS: "Good", ALERTNODES: [10] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [2, 5] },
  { SLOTID: "SLOTID8", STATUS: "Good", ALERTNODES: [1, 8, 12] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [3] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [8, 10] },
  { SLOTID: "SLOTID5", STATUS: "Good", ALERTNODES: [1, 13] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [4] },
  { SLOTID: "SLOTID7", STATUS: "Degraded", ALERTNODES: [2, 9] },
  { SLOTID: "SLOTID3", STATUS: "Start to degrade", ALERTNODES: [5, 14] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [3, 6, 15] },
  { SLOTID: "SLOTID5", STATUS: "Good", ALERTNODES: [3, 5, 11] },
  { SLOTID: "SLOTID7", STATUS: "Degraded", ALERTNODES: [6] },
  { SLOTID: "SLOTID6", STATUS: "Average", ALERTNODES: [1, 16] },
  { SLOTID: "SLOTID5", STATUS: "Average", ALERTNODES: [4, 5, 9] },
  { SLOTID: "SLOTID1", STATUS: "Degraded", ALERTNODES: [9, 13] },
  { SLOTID: "SLOTID6", STATUS: "Good", ALERTNODES: [10, 15] },
  { SLOTID: "SLOTID4", STATUS: "Good", ALERTNODES: [1, 13, 15] },
  { SLOTID: "SLOTID2", STATUS: "Good", ALERTNODES: [6, 7, 9] },
  { SLOTID: "SLOTID7", STATUS: "Average", ALERTNODES: [5, 16] },
  { SLOTID: "SLOTID2", STATUS: "Good", ALERTNODES: [14] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [7, 10] },
  { SLOTID: "SLOTID4", STATUS: "Degraded", ALERTNODES: [2, 7, 9] },
  { SLOTID: "SLOTID2", STATUS: "Good", ALERTNODES: [4, 5] },
  { SLOTID: "SLOTID5", STATUS: "Degraded", ALERTNODES: [6, 15] },
  { SLOTID: "SLOTID5", STATUS: "Good", ALERTNODES: [12, 15] },
  { SLOTID: "SLOTID2", STATUS: "Start to degrade", ALERTNODES: [9] },
  { SLOTID: "SLOTID2", STATUS: "Degraded", ALERTNODES: [11, 15] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [3, 6, 10] },
  { SLOTID: "SLOTID6", STATUS: "Degraded", ALERTNODES: [9, 12] },
  { SLOTID: "SLOTID7", STATUS: "Start to degrade", ALERTNODES: [14] },
  { SLOTID: "SLOTID1", STATUS: "Good", ALERTNODES: [11] },
  { SLOTID: "SLOTID1", STATUS: "Degraded", ALERTNODES: [14] },
  { SLOTID: "SLOTID2", STATUS: "Good", ALERTNODES: [16] },
  { SLOTID: "SLOTID5", STATUS: "Average", ALERTNODES: [5] },
  { SLOTID: "SLOTID8", STATUS: "Start to degrade", ALERTNODES: [6, 7, 14] },
  { SLOTID: "SLOTID4", STATUS: "Start to degrade", ALERTNODES: [2, 10] },
  { SLOTID: "SLOTID1", STATUS: "Good", ALERTNODES: [1, 13] },
  { SLOTID: "SLOTID6", STATUS: "Average", ALERTNODES: [3, 10, 16] },
  { SLOTID: "SLOTID2", STATUS: "Good", ALERTNODES: [3, 4] },
  { SLOTID: "SLOTID3", STATUS: "Degraded", ALERTNODES: [4, 6, 16] },
  { SLOTID: "SLOTID2", STATUS: "Start to degrade", ALERTNODES: [3, 14] },
  { SLOTID: "SLOTID3", STATUS: "Degraded", ALERTNODES: [4] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [4, 13] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [6] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [6] },
  { SLOTID: "SLOTID6", STATUS: "Good", ALERTNODES: [6, 11] },
  { SLOTID: "SLOTID3", STATUS: "Degraded", ALERTNODES: [5] },
  { SLOTID: "SLOTID4", STATUS: "Start to degrade", ALERTNODES: [4, 8] },
  { SLOTID: "SLOTID4", STATUS: "Degraded", ALERTNODES: [11, 12, 15] },
  { SLOTID: "SLOTID4", STATUS: "Average", ALERTNODES: [1, 2, 10] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [3, 6] },
  { SLOTID: "SLOTID1", STATUS: "Average", ALERTNODES: [2, 6, 14] },
  { SLOTID: "SLOTID1", STATUS: "Good", ALERTNODES: [4, 14] },
  { SLOTID: "SLOTID3", STATUS: "Degraded", ALERTNODES: [11] },
  { SLOTID: "SLOTID6", STATUS: "Average", ALERTNODES: [13, 15] },
  { SLOTID: "SLOTID8", STATUS: "Average", ALERTNODES: [4, 15] },
  { SLOTID: "SLOTID1", STATUS: "Degraded", ALERTNODES: [2, 5, 13] },
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [3, 15] },
  { SLOTID: "SLOTID5", STATUS: "Average", ALERTNODES: [11, 13] },
  { SLOTID: "SLOTID6", STATUS: "Good", ALERTNODES: [11] },
  { SLOTID: "SLOTID4", STATUS: "Degraded", ALERTNODES: [6, 13] },
  { SLOTID: "SLOTID1", STATUS: "Good", ALERTNODES: [4, 11, 14] },
  { SLOTID: "SLOTID5", STATUS: "Degraded", ALERTNODES: [1] },
  { SLOTID: "SLOTID5", STATUS: "Average", ALERTNODES: [4, 5] },
  { SLOTID: "SLOTID6", STATUS: "Average", ALERTNODES: [5] },
  { SLOTID: "SLOTID3", STATUS: "Start to degrade", ALERTNODES: [3, 16] },
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [9, 13, 15] },
  { SLOTID: "SLOTID8", STATUS: "Start to degrade", ALERTNODES: [4, 8] },
  { SLOTID: "SLOTID4", STATUS: "Average", ALERTNODES: [13] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [6] },
  { SLOTID: "SLOTID4", STATUS: "Degraded", ALERTNODES: [4, 7, 9] },
  { SLOTID: "SLOTID2", STATUS: "Degraded", ALERTNODES: [7, 9] },
  { SLOTID: "SLOTID1", STATUS: "Degraded", ALERTNODES: [4, 7, 12] },
  { SLOTID: "SLOTID4", STATUS: "Good", ALERTNODES: [6, 7, 16] },
  { SLOTID: "SLOTID4", STATUS: "Degraded", ALERTNODES: [1, 6, 9] },
  { SLOTID: "SLOTID1", STATUS: "Good", ALERTNODES: [2] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [9, 15] },
  { SLOTID: "SLOTID7", STATUS: "Average", ALERTNODES: [8, 13, 15] },
  { SLOTID: "SLOTID8", STATUS: "Start to degrade", ALERTNODES: [6] },
  { SLOTID: "SLOTID5", STATUS: "Good", ALERTNODES: [13] },
  { SLOTID: "SLOTID3", STATUS: "Degraded", ALERTNODES: [1, 9, 12] },
  { SLOTID: "SLOTID4", STATUS: "Start to degrade", ALERTNODES: [12] },
  { SLOTID: "SLOTID1", STATUS: "Good", ALERTNODES: [10, 15] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [4, 16] },
  { SLOTID: "SLOTID1", STATUS: "Start to degrade", ALERTNODES: [14] },
  { SLOTID: "SLOTID6", STATUS: "Good", ALERTNODES: [15, 16] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [7] },
  { SLOTID: "SLOTID2", STATUS: "Good", ALERTNODES: [11] },
  { SLOTID: "SLOTID8", STATUS: "Good", ALERTNODES: [3, 6, 11] },
  { SLOTID: "SLOTID1", STATUS: "Degraded", ALERTNODES: [1, 3] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [15] },
  { SLOTID: "SLOTID5", STATUS: "Good", ALERTNODES: [2, 10] },
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [8, 10, 12] },
  { SLOTID: "SLOTID1", STATUS: "Degraded", ALERTNODES: [1, 9, 13] },
  { SLOTID: "SLOTID1", STATUS: "Good", ALERTNODES: [6, 11, 14] },
  { SLOTID: "SLOTID2", STATUS: "Start to degrade", ALERTNODES: [5, 13] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [2, 10, 14] },
  { SLOTID: "SLOTID4", STATUS: "Good", ALERTNODES: [3, 7, 16] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [6, 7, 9] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [15] },
  { SLOTID: "SLOTID6", STATUS: "Good", ALERTNODES: [1, 5, 15] },
  { SLOTID: "SLOTID7", STATUS: "Start to degrade", ALERTNODES: [10] },
  { SLOTID: "SLOTID8", STATUS: "Good", ALERTNODES: [9] },
  { SLOTID: "SLOTID1", STATUS: "Start to degrade", ALERTNODES: [1, 2, 14] },
  { SLOTID: "SLOTID7", STATUS: "Start to degrade", ALERTNODES: [2, 5, 9] },
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [3] },
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [10] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [3, 4, 15] },
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [8, 9] },
  { SLOTID: "SLOTID6", STATUS: "Average", ALERTNODES: [9] },
  { SLOTID: "SLOTID6", STATUS: "Start to degrade", ALERTNODES: [10, 12, 15] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [14] },
  { SLOTID: "SLOTID2", STATUS: "Degraded", ALERTNODES: [13] },
  { SLOTID: "SLOTID4", STATUS: "Start to degrade", ALERTNODES: [14, 15] },
  { SLOTID: "SLOTID8", STATUS: "Average", ALERTNODES: [1, 3, 14] },
  { SLOTID: "SLOTID6", STATUS: "Degraded", ALERTNODES: [4, 9] },
  { SLOTID: "SLOTID6", STATUS: "Good", ALERTNODES: [7, 11] },
  { SLOTID: "SLOTID6", STATUS: "Degraded", ALERTNODES: [1, 13] },
  { SLOTID: "SLOTID7", STATUS: "Average", ALERTNODES: [5] },
  { SLOTID: "SLOTID6", STATUS: "Start to degrade", ALERTNODES: [1, 12, 13] },
  { SLOTID: "SLOTID8", STATUS: "Start to degrade", ALERTNODES: [6, 9] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [13, 15] },
  { SLOTID: "SLOTID8", STATUS: "Average", ALERTNODES: [1, 4, 11] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [2, 8, 14] },
  { SLOTID: "SLOTID4", STATUS: "Average", ALERTNODES: [10] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [12] },
  { SLOTID: "SLOTID7", STATUS: "Average", ALERTNODES: [7, 10] },
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [5, 6, 8] },
  { SLOTID: "SLOTID7", STATUS: "Degraded", ALERTNODES: [11] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [3, 6] },
  { SLOTID: "SLOTID8", STATUS: "Good", ALERTNODES: [1] },
  { SLOTID: "SLOTID8", STATUS: "Start to degrade", ALERTNODES: [1] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [4] },
  { SLOTID: "SLOTID1", STATUS: "Start to degrade", ALERTNODES: [2, 6] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [1] },
  { SLOTID: "SLOTID6", STATUS: "Degraded", ALERTNODES: [4, 11] },
  { SLOTID: "SLOTID1", STATUS: "Average", ALERTNODES: [9] },
  { SLOTID: "SLOTID2", STATUS: "Good", ALERTNODES: [4, 5, 9] },
  { SLOTID: "SLOTID3", STATUS: "Start to degrade", ALERTNODES: [16] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [5] },
  { SLOTID: "SLOTID8", STATUS: "Average", ALERTNODES: [8] },
  { SLOTID: "SLOTID1", STATUS: "Average", ALERTNODES: [7, 8] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [1, 9] },
  { SLOTID: "SLOTID1", STATUS: "Degraded", ALERTNODES: [2, 12] },
  { SLOTID: "SLOTID1", STATUS: "Average", ALERTNODES: [15] },
  { SLOTID: "SLOTID6", STATUS: "Average", ALERTNODES: [6, 11] },
  { SLOTID: "SLOTID5", STATUS: "Good", ALERTNODES: [5] },
  { SLOTID: "SLOTID6", STATUS: "Good", ALERTNODES: [4, 16] },
  { SLOTID: "SLOTID1", STATUS: "Average", ALERTNODES: [10, 15] },
  { SLOTID: "SLOTID6", STATUS: "Degraded", ALERTNODES: [2, 6, 15] },
  { SLOTID: "SLOTID6", STATUS: "Good", ALERTNODES: [7, 13, 15] },
  { SLOTID: "SLOTID8", STATUS: "Average", ALERTNODES: [3, 10] },
  { SLOTID: "SLOTID5", STATUS: "Good", ALERTNODES: [8, 10] },
  { SLOTID: "SLOTID3", STATUS: "Start to degrade", ALERTNODES: [13] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [4] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [8] },
  { SLOTID: "SLOTID1", STATUS: "Good", ALERTNODES: [6, 7, 15] },
  { SLOTID: "SLOTID1", STATUS: "Average", ALERTNODES: [3] },
  { SLOTID: "SLOTID5", STATUS: "Average", ALERTNODES: [7] },
  { SLOTID: "SLOTID3", STATUS: "Average", ALERTNODES: [3, 10] },
  { SLOTID: "SLOTID7", STATUS: "Start to degrade", ALERTNODES: [8, 9, 13] },
  { SLOTID: "SLOTID6", STATUS: "Start to degrade", ALERTNODES: [16] },
  { SLOTID: "SLOTID5", STATUS: "Good", ALERTNODES: [2, 7, 8] },
  { SLOTID: "SLOTID4", STATUS: "Average", ALERTNODES: [6] },
  { SLOTID: "SLOTID6", STATUS: "Good", ALERTNODES: [10, 16] },
  { SLOTID: "SLOTID4", STATUS: "Start to degrade", ALERTNODES: [2, 13] },
  { SLOTID: "SLOTID2", STATUS: "Degraded", ALERTNODES: [7] },
  { SLOTID: "SLOTID8", STATUS: "Start to degrade", ALERTNODES: [13] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [15] },
  { SLOTID: "SLOTID6", STATUS: "Average", ALERTNODES: [3, 6] },
  { SLOTID: "SLOTID5", STATUS: "Average", ALERTNODES: [15] },
  { SLOTID: "SLOTID6", STATUS: "Start to degrade", ALERTNODES: [1, 11, 16] },
  { SLOTID: "SLOTID7", STATUS: "Start to degrade", ALERTNODES: [1, 8, 16] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [1, 14] },
  { SLOTID: "SLOTID7", STATUS: "Start to degrade", ALERTNODES: [3, 11] },
  { SLOTID: "SLOTID3", STATUS: "Start to degrade", ALERTNODES: [9, 10, 11] },
  { SLOTID: "SLOTID3", STATUS: "Average", ALERTNODES: [9, 12, 15] },
  { SLOTID: "SLOTID8", STATUS: "Degraded", ALERTNODES: [8, 9, 16] },
  { SLOTID: "SLOTID2", STATUS: "Good", ALERTNODES: [6, 9, 16] },
  { SLOTID: "SLOTID4", STATUS: "Degraded", ALERTNODES: [10, 14] },
  { SLOTID: "SLOTID1", STATUS: "Average", ALERTNODES: [9, 12, 13] },
  { SLOTID: "SLOTID1", STATUS: "Start to degrade", ALERTNODES: [3, 8, 16] },
  { SLOTID: "SLOTID8", STATUS: "Average", ALERTNODES: [5, 7, 11] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [4, 5, 8] },
  { SLOTID: "SLOTID7", STATUS: "Degraded", ALERTNODES: [4, 5] },
  { SLOTID: "SLOTID7", STATUS: "Average", ALERTNODES: [5, 7, 9] },
  { SLOTID: "SLOTID1", STATUS: "Good", ALERTNODES: [2, 13, 15] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [3, 11, 12] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [5, 12, 13] },
  { SLOTID: "SLOTID3", STATUS: "Average", ALERTNODES: [10] },
  { SLOTID: "SLOTID5", STATUS: "Degraded", ALERTNODES: [9] },
  { SLOTID: "SLOTID5", STATUS: "Good", ALERTNODES: [8, 14, 16] },
  { SLOTID: "SLOTID1", STATUS: "Degraded", ALERTNODES: [4] },
  { SLOTID: "SLOTID5", STATUS: "Start to degrade", ALERTNODES: [7] },
  { SLOTID: "SLOTID2", STATUS: "Good", ALERTNODES: [2, 6, 15] },
  { SLOTID: "SLOTID4", STATUS: "Average", ALERTNODES: [7] },
  { SLOTID: "SLOTID5", STATUS: "Average", ALERTNODES: [2, 5] },
  { SLOTID: "SLOTID4", STATUS: "Average", ALERTNODES: [3, 5, 12] },
  { SLOTID: "SLOTID8", STATUS: "Good", ALERTNODES: [7] },
  { SLOTID: "SLOTID7", STATUS: "Good", ALERTNODES: [14] },
  { SLOTID: "SLOTID3", STATUS: "Average", ALERTNODES: [3, 13] },
  { SLOTID: "SLOTID6", STATUS: "Start to degrade", ALERTNODES: [3, 14] },
  { SLOTID: "SLOTID5", STATUS: "Average", ALERTNODES: [6, 7] },
  { SLOTID: "SLOTID3", STATUS: "Average", ALERTNODES: [3] },
  { SLOTID: "SLOTID1", STATUS: "Degraded", ALERTNODES: [5] },
  { SLOTID: "SLOTID2", STATUS: "Average", ALERTNODES: [5, 6] },
  { SLOTID: "SLOTID4", STATUS: "Start to degrade", ALERTNODES: [7, 10] },
  { SLOTID: "SLOTID2", STATUS: "Good", ALERTNODES: [5, 16] },
  { SLOTID: "SLOTID3", STATUS: "Degraded", ALERTNODES: [3, 6, 9] },
  { SLOTID: "SLOTID6", STATUS: "Start to degrade", ALERTNODES: [2, 7] },
  { SLOTID: "SLOTID2", STATUS: "Start to degrade", ALERTNODES: [2, 7] },
  { SLOTID: "SLOTID3", STATUS: "Good", ALERTNODES: [7, 10] },
];

export default data;
